# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-09-01 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='category',
        ),
    ]
